import type { AppProps } from 'next/app';
import Head from 'next/head';
import Footer from '../components/footer/Footer';
import { Modal } from '../components/modal';
import Navbar from '../components/navbar/Navbar';
import ScrollToTheTop from '../components/scroll-top/ScrollToTheTop';
import '../styles/globals.scss';

function MyApp({ Component, pageProps }: AppProps) {
  return (
    <>
      <Head>
        <title>Dicoogle - Open-source PACS</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Navbar />
      <Component {...pageProps} />

      <Footer />

      <ScrollToTheTop />

      <Modal />
    </>
  );
}

export default MyApp;
